#cloud-config

# GENERAL #

# Allow duplicate keys in this file to be merged together.
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

# Update apt-get repos and upgrade packages on first boot; allow reboots during install.
package_update: true
package_upgrade: true
package_reboot_if_required: true

# DATA DISK CONFIGURATION #
disk_setup:
  /dev/disk/azure/scsi1/lun0:
    table_type: gpt
    layout: True
    overwrite: True
fs_setup:
  - device: /dev/disk/azure/scsi1/lun0
    partition: 1
    filesystem: ext4
mounts:
    - ["/dev/disk/azure/scsi1/lun0-part1", "/var", auto, "defaults,noexec,nofail"]

# DOCKER INSTALLATION #
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]


# PYTHON INSTALLATION #
packages:
  - make 
  - build-essential 
  - libssl-dev 
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev

runcmd:
  - |
    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash;
    export PATH="$HOME/.pyenv/bin:$PATH";
    exec $shell;
    pyenv install 3.8.6;

write_files:
  - path: /home/vm-root/.bashrc
