#include
https://raw.githubusercontent.com/SkillUpTech/arm-templates/main/common/cloud-init/focal/base.yaml
https://raw.githubusercontent.com/SkillUpTech/arm-templates/main/common/cloud-init/focal/lun0-disk.yaml
https://raw.githubusercontent.com/SkillUpTech/arm-templates/main/common/cloud-init/focal/python38.yaml
https://raw.githubusercontent.com/SkillUpTech/arm-templates/main/common/cloud-init/focal/docker-storage.yaml
https://raw.githubusercontent.com/SkillUpTech/arm-templates/main/common/cloud-init/focal/docker.yaml
