#cloud-config
packages:
  - python3-pip
  - python3.8
  - python3.8-dev
  - python3.8-distutils
  - python3.8-venv
runcmd:
  - sudo -u vm-root python3 -m pip install --user pipx
  - sudo -u vm-root python3 -m pipx ensurepath
